"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, CheckCircle2, Loader2, Search, ShieldCheck, X } from "lucide-react";
import { getAppAuthHeaders, getAppSession, hasAppPermission } from "@/lib/client-auth";

type Person = { id:string; name:string; birth_number:string; rank_id:string|null; rank_name:string|null; rank_effective_at:string|null };
type Rank = { id:string; name:string; rank_level:number };
const date = (value:string|null) => value ? new Intl.DateTimeFormat("en-GB",{dateStyle:"long"}).format(new Date(value)) : "Not recorded";

export default function RankCorrectionsPage(){
  const router=useRouter();
  const [people,setPeople]=useState<Person[]>([]),[ranks,setRanks]=useState<Rank[]>([]),[selectedId,setSelectedId]=useState(""),[rankId,setRankId]=useState(""),[reason,setReason]=useState(""),[query,setQuery]=useState(""),[access,setAccess]=useState("none"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[reviewing,setReviewing]=useState(false),[message,setMessage]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/admin/rank-corrections",{cache:"no-store",headers:await getAppAuthHeaders()});const body=await response.json();if(!response.ok)throw new Error(body.error||"Failed to load rank correction data");setPeople(body.personnel);setRanks(body.ranks);},[]);
  useEffect(()=>{void(async()=>{const session=await getAppSession();if(!session||!hasAppPermission(session,"admin.rank-corrections","read"))return router.replace(session?"/":"/login");setAccess(session.permissions["admin.rank-corrections"]||"none");try{await load();}catch(caught){setMessage(caught instanceof Error?caught.message:"Failed to load rank correction data");}finally{setLoading(false);}})()},[load,router]);
  const filtered=useMemo(()=>people.filter(person=>`${person.name} ${person.birth_number}`.toLowerCase().includes(query.toLowerCase())).slice(0,80),[people,query]);
  const selected=people.find(person=>person.id===selectedId)||null,nextRank=ranks.find(rank=>rank.id===rankId)||null;
  async function apply(){if(!selected||!nextRank)return;setSaving(true);setMessage("");const response=await fetch("/api/admin/rank-corrections",{method:"POST",headers:{"Content-Type":"application/json",...(await getAppAuthHeaders())},body:JSON.stringify({personnelId:selected.id,rankId:nextRank.id,reason})});const body=await response.json().catch(()=>null) as {error?:string}|null;setSaving(false);if(!response.ok)return setMessage(body?.error||"Failed to correct rank");setReviewing(false);setReason("");setRankId("");setMessage(`${selected.name} is now ${nextRank.name}. TIG was preserved.`);await load();}
  if(loading)return <main className="min-h-screen bg-[#020806] p-10 text-[#00ff66]">Loading rank corrections...</main>;
  const canEdit=access==="edit"||access==="full";
  return <main className="min-h-screen bg-[#020806] px-4 py-10 text-white sm:px-8"><section className="mx-auto max-w-7xl border border-[#00ff66]/25 bg-black/80"><header className="flex items-center gap-4 border-b border-[#00ff66]/20 p-6"><ShieldCheck className="text-[#00ff66]"/><div><p className="text-xs uppercase tracking-[.22em] text-[#00ff66]">Personnel Administration</p><h1 className="text-3xl font-black uppercase">Rank Corrections</h1></div></header>{message&&<div className="border-b border-cyan-400/20 bg-cyan-400/5 px-6 py-3 text-cyan-200">{message}</div>}
  <div className="grid min-h-[640px] lg:grid-cols-[380px_1fr]"><section className="border-b border-[#00ff66]/15 p-5 lg:border-b-0 lg:border-r"><div className="relative"><Search size={17} className="absolute left-3 top-3.5 text-gray-500"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search name or service number" className="w-full border border-white/10 bg-[#030b07] py-3 pl-10 pr-3 outline-none focus:border-[#00ff66]/50"/></div><div className="mt-4 max-h-[540px] divide-y divide-white/10 overflow-y-auto border border-white/10">{filtered.map(person=><button key={person.id} onClick={()=>{setSelectedId(person.id);setRankId("");setReason("");}} className={`w-full p-4 text-left transition ${selectedId===person.id?"bg-[#00ff66]/10 text-[#00ff66]":"hover:bg-white/[.03]"}`}><strong className="block">{person.name}</strong><span className="mt-1 block text-xs text-gray-500">{person.birth_number} · {person.rank_name||"Unranked"}</span></button>)}</div></section>
  <section className="p-6 sm:p-8">{selected?<div className="max-w-3xl"><div className="grid gap-px bg-[#00ff66]/15 sm:grid-cols-2"><div className="bg-[#020806] p-5"><p className="text-xs uppercase tracking-[.18em] text-gray-500">Current rank</p><p className="mt-2 text-xl font-bold">{selected.rank_name||"Unranked"}</p></div><div className="bg-[#020806] p-5"><p className="text-xs uppercase tracking-[.18em] text-gray-500">TIG effective date</p><p className="mt-2 text-xl font-bold text-[#00ff66]">{date(selected.rank_effective_at)}</p></div></div><label className="mt-6 block"><span className="text-xs font-bold uppercase tracking-[.18em] text-gray-400">Correct rank to</span><select value={rankId} onChange={event=>setRankId(event.target.value)} disabled={!canEdit} className="mt-2 w-full border border-[#00ff66]/25 bg-black p-4 outline-none focus:border-[#00ff66]"><option value="">Select rank</option>{ranks.filter(rank=>rank.id!==selected.rank_id).map(rank=><option key={rank.id} value={rank.id}>{rank.name}</option>)}</select></label><label className="mt-5 block"><span className="text-xs font-bold uppercase tracking-[.18em] text-gray-400">Correction reason</span><textarea value={reason} onChange={event=>setReason(event.target.value)} disabled={!canEdit} maxLength={500} className="mt-2 min-h-32 w-full border border-[#00ff66]/25 bg-black p-4 outline-none focus:border-[#00ff66]" placeholder="Reason for correcting the recorded rank"/></label><button onClick={()=>setReviewing(true)} disabled={!canEdit||!nextRank||reason.trim().length<3} className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 border border-[#00ff66]/40 bg-[#00ff66]/10 font-bold uppercase tracking-[.14em] text-[#00ff66] disabled:opacity-40"><ShieldCheck size={18}/>Review correction</button></div>:<div className="grid min-h-[480px] place-items-center border border-dashed border-white/10 text-gray-500">Select personnel to begin.</div>}</section></div></section>
  {reviewing&&selected&&nextRank&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/90 p-4 backdrop-blur-sm"><section role="dialog" aria-modal="true" className="w-full max-w-xl border border-[#00ff66]/30 bg-[#020806]"><header className="flex items-start justify-between border-b border-[#00ff66]/15 p-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#00ff66]">Confirm rank correction</p><h2 className="mt-2 text-2xl font-black">{selected.name}</h2></div><button onClick={()=>setReviewing(false)} className="grid h-10 w-10 place-items-center border border-white/10 text-gray-400"><X size={18}/></button></header><div className="p-5"><div className="flex items-center justify-between gap-4 border border-white/10 bg-white/[.02] p-5"><strong>{selected.rank_name||"Unranked"}</strong><ArrowRight className="text-[#00ff66]"/><strong className="text-[#00ff66]">{nextRank.name}</strong></div><div className="mt-4 border border-amber-300/25 bg-amber-300/5 p-4 text-sm text-amber-100">TIG remains {date(selected.rank_effective_at)}.</div><p className="mt-4 text-sm leading-6 text-gray-400">{reason}</p></div><footer className="grid grid-cols-2 gap-3 border-t border-white/10 p-4"><button onClick={()=>setReviewing(false)} className="min-h-11 border border-white/15 text-gray-300">Back</button><button onClick={()=>void apply()} disabled={saving} className="flex min-h-11 items-center justify-center gap-2 border border-[#00ff66]/40 bg-[#00ff66]/10 font-bold uppercase text-[#00ff66]">{saving?<Loader2 className="animate-spin" size={17}/>:<CheckCircle2 size={17}/>}Confirm</button></footer></section></div>}
  </main>;
}
