const CERTIFICATION_FAMILIES: Record<string, string> = {
  "AV-7": "IDF",
  "Advanced AT": "Anti-Tank",
  "Advanced AT Trainer": "Anti-Tank",
  "Anti-Tank": "Anti-Tank",
  "AT Trainer": "Anti-Tank",
  "Advanced Grenadier": "Grenadier",
  "Advanced Grenadier Trainer": "Grenadier",
  Grenadier: "Grenadier",
  "Grenadier Trainer": "Grenadier",
  "Advanced Marksman": "Marksman",
  "Advanced Marksman Trainer": "Marksman",
  Marksman: "Marksman",
  "Marksman Instructor": "Marksman",
  "Advanced Support": "Support",
  "Advanced Support Trainer": "Support",
  Support: "Support",
  "Support Trainer": "Support",
  "Combat Engineer": "Combat Engineer",
  "Combat Engineer Trainer": "Combat Engineer",
  "Drone Operator": "Drone",
  "Drone Operator Trainer": "Drone",
  "Weaponized Drone": "Drone",
  "EU Recruiter": "Recruitment",
  "NA Recruiter": "Recruitment",
  "Senior Recruiter": "Recruitment",
  Forge: "Forge",
  "Forge Trainer": "Forge",
  IDF: "IDF",
  "IDF Trainer": "IDF",
  IFV: "IFV",
  "IFV Trainer": "IFV",
  "Mission Builder": "Mission Builder",
  "Mission Builder Trainer": "Mission Builder",
  "LAAT Qual": "LAAT",
  Rotorcraft: "LAAT",
  RTO: "RTO",
  "RTO Trainer": "RTO",
  "VTOL Qual": "VTOL",
  "VTOL Trainer": "VTOL",
  CLS: "Medical",
  "Medic Trainer": "Medical",
  "Zeus Trainee": "Zeus",
  "Zeus Certified": "Zeus",
  "Senior Zeus": "Zeus",
  "Zeus Trainer": "Zeus",
};

export function getCertificationFamilyName(certificationName: string) {
  return CERTIFICATION_FAMILIES[certificationName] || certificationName;
}
