"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { Activity,History,Loader2,Search,TrendingUp } from "lucide-react";
import { getAppAuthHeaders,getAppSession,hasAppPermission } from "@/lib/client-auth";
type Person={id:string;name:string;rank_name:string|null;total_xp:number;current_level:number;last_event_at:string|null};
type Adjustment={id:string;personnel_id:string;name:string;xp_delta:number;previous_total:number;new_total:number;reason:string;adjusted_by_name:string;created_at:string};
const fmt=(v:string)=>new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
export default function XpManagementPage(){const router=useRouter(),[people,setPeople]=useState<Person[]>([]),[history,setHistory]=useState<Adjustment[]>([]),[query,setQuery]=useState(""),[selected,setSelected]=useState(""),[delta,setDelta]=useState(""),[reason,setReason]=useState(""),[access,setAccess]=useState("none"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
const load=useCallback(async()=>{const r=await fetch("/api/admin/xp",{cache:"no-store",headers:await getAppAuthHeaders()}),b=await r.json();if(!r.ok)throw new Error(b.error||"Failed to load XP data");setPeople(b.personnel);setHistory(b.adjustments);},[]);
useEffect(()=>{void(async()=>{const s=await getAppSession();if(!s||!hasAppPermission(s,"admin.xp","read"))return router.replace(s?"/":"/login");setAccess(s.permissions["admin.xp"]||"none");try{await load();}catch(e){setMessage(e instanceof Error?e.message:"Failed to load XP data");}finally{setLoading(false);}})()},[load,router]);
const filtered=useMemo(()=>people.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).slice(0,30),[people,query]);
async function apply(){setSaving(true);setMessage("");const r=await fetch("/api/admin/xp",{method:"POST",headers:{"Content-Type":"application/json",...(await getAppAuthHeaders())},body:JSON.stringify({personnelId:selected,xpDelta:Number(delta),reason})}),b=await r.json();setSaving(false);if(!r.ok)return setMessage(b.error||"Correction failed");setDelta("");setReason("");setMessage("XP correction applied and audited.");await load();}
return <main className="min-h-screen bg-[#020806] px-4 py-10 text-white sm:px-8"><section className="mx-auto max-w-7xl border border-[#00ff66]/25 bg-black/80"><header className="flex items-center gap-4 border-b border-[#00ff66]/20 p-6"><Activity className="text-[#00ff66]"/><div><p className="text-xs uppercase tracking-[.22em] text-[#00ff66]">Arma Bridge</p><h1 className="text-3xl font-black uppercase">XP Management</h1></div></header>{message&&<div className="border-b border-cyan-400/20 bg-cyan-400/5 p-4 text-cyan-200">{message}</div>}
<div className="grid lg:grid-cols-[1fr_1.1fr]"><section className="border-b border-[#00ff66]/15 p-6 lg:border-b-0 lg:border-r"><h2 className="mb-4 flex items-center gap-2 font-bold uppercase"><TrendingUp size={18} className="text-[#00ff66]"/>Apply correction</h2><div className="relative mb-3"><Search className="absolute left-3 top-3.5 text-gray-500" size={17}/><input className="w-full border border-white/10 bg-[#030b07] py-3 pl-10 pr-3" placeholder="Search active personnel" value={query} onChange={e=>setQuery(e.target.value)}/></div><select className="mb-3 w-full border border-white/10 bg-[#030b07] p-3" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select personnel</option>{filtered.map(p=><option key={p.id} value={p.id}>{p.name} · L{p.current_level} · {p.total_xp} XP</option>)}</select><input type="number" className="mb-3 w-full border border-white/10 bg-[#030b07] p-3" placeholder="XP adjustment, e.g. 500 or -250" value={delta} onChange={e=>setDelta(e.target.value)}/><textarea className="min-h-28 w-full border border-white/10 bg-[#030b07] p-3" placeholder="Required correction reason" value={reason} onChange={e=>setReason(e.target.value)}/><button disabled={saving||!selected||!delta||reason.trim().length<3||access==="read"} onClick={apply} className="mt-4 flex w-full items-center justify-center gap-2 border border-[#00ff66]/40 bg-[#00ff66]/10 p-3 text-[#00ff66] disabled:opacity-40">{saving?<Loader2 className="animate-spin" size={18}/>:<Activity size={18}/>}Apply audited correction</button></section>
<section className="p-6"><h2 className="mb-4 flex items-center gap-2 font-bold uppercase"><History size={18} className="text-[#00ff66]"/>Recent corrections</h2><div className="max-h-[620px] divide-y divide-white/10 overflow-y-auto border border-white/10">{history.map(row=><article key={row.id} className="p-4"><div className="flex justify-between gap-3"><strong>{row.name}</strong><span className={row.xp_delta>=0?"text-[#00ff66]":"text-red-300"}>{row.xp_delta>=0?"+":""}{row.xp_delta} XP</span></div><p className="mt-2 text-sm text-gray-300">{row.reason}</p><p className="mt-2 text-xs text-gray-500">{row.previous_total} → {row.new_total} · {row.adjusted_by_name} · {fmt(row.created_at)}</p></article>)}{!history.length&&!loading&&<p className="p-5 text-gray-400">No corrections recorded.</p>}</div></section></div></section></main>}
