import {NextResponse} from "next/server";
import {getPostgresPool} from "@/lib/postgres/pool";
import {requestHasSameOrigin,requirePageAccess} from "@/lib/route-permissions";
import {supabaseAdmin} from "@/lib/supabase-admin";
export const runtime="nodejs";export const dynamic="force-dynamic";const KEY="operations.planops",UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,MAPS=new Set(["altis","tanoa","malden"]),TYPES=new Set(["infantry","vehicle","objective","support","note"]);
function backend(){const v=process.env.PLANOPS_DATABASE_BACKEND||"supabase";if(v!=="postgres"&&v!=="supabase")throw new Error("Unknown PLANOPS_DATABASE_BACKEND");return v;}
function layers(v:unknown){if(!Array.isArray(v)||v.length>50)return null;const out=[];for(const x of v){const r=x as Record<string,unknown>,id=String(r.id||"").slice(0,100),name=String(r.name||"").trim().slice(0,100);if(!id||!name||typeof r.visible!=="boolean")return null;out.push({id,name,visible:r.visible});}return out;}
function markers(v:unknown){if(!Array.isArray(v)||v.length>1000)return null;const out=[];for(const x of v){const r=x as Record<string,unknown>,id=String(r.id||"").slice(0,100),type=String(r.type||""),layerId=String(r.layerId||"").slice(0,100),xv=Number(r.x),yv=Number(r.y),color=String(r.color||"");if(!id||!layerId||!TYPES.has(type)||!Number.isFinite(xv)||!Number.isFinite(yv)||!/^#[0-9a-f]{6}$/i.test(color))return null;out.push({id,x:Math.max(0,Math.min(10000,xv)),y:Math.max(0,Math.min(10000,yv)),label:String(r.label||"").slice(0,200),type,color,layerId});}return out;}
function input(v:unknown){const b=v as Record<string,unknown>|null,name=String(b?.name||"").trim().slice(0,200),map=String(b?.map_name||""),ls=layers(b?.layers),ms=markers(b?.markers);if(!name||!MAPS.has(map)||!ls||!ms)return null;return{name,notes:String(b?.notes||"").slice(0,10000)||null,map_name:map,layers:ls,markers:ms};}
export async function GET(request:Request){if(!(await requirePageAccess(request,KEY,"read").catch(()=>null)))return NextResponse.json({error:"Forbidden"},{status:403});const id=new URL(request.url).searchParams.get("id");if(id&&!UUID.test(id))return NextResponse.json({error:"Invalid plan"},{status:400});try{if(backend()==="postgres"){const r=await getPostgresPool().query(`select * from public.operation_plans ${id?"where id=$1":""} order by updated_at desc`,id?[id]:[]);return NextResponse.json({plans:r.rows},{headers:{"Cache-Control":"no-store"}});}let q=supabaseAdmin.from("operation_plans").select("*");if(id)q=q.eq("id",id);const r=await q.order("updated_at",{ascending:false});if(r.error)throw r.error;return NextResponse.json({plans:r.data||[]},{headers:{"Cache-Control":"no-store"}});}catch(e){console.error("[planops] Read failed",e);return NextResponse.json({error:"Failed to load plans"},{status:500});}}
export async function POST(request:Request){if(!requestHasSameOrigin(request))return NextResponse.json({error:"Invalid request origin"},{status:403});const auth=await requirePageAccess(request,KEY,"edit").catch(()=>null);if(!auth)return NextResponse.json({error:"Forbidden"},{status:403});const data=input(await request.json().catch(()=>null));if(!data)return NextResponse.json({error:"Invalid plan"},{status:400});try{if(backend()==="postgres"){const r=await getPostgresPool().query("insert into public.operation_plans(name,notes,map_name,layers,markers,created_by) values($1,$2,$3,$4::jsonb,$5::jsonb,$6) returning *",[data.name,data.notes,data.map_name,JSON.stringify(data.layers),JSON.stringify(data.markers),auth.userId]);return NextResponse.json({plan:r.rows[0]},{status:201});}const r=await supabaseAdmin.from("operation_plans").insert({...data,created_by:auth.userId}).select().single();if(r.error)throw r.error;return NextResponse.json({plan:r.data},{status:201});}catch(e){console.error("[planops] Create failed",e);return NextResponse.json({error:"Failed to create plan"},{status:500});}}
export async function PATCH(request:Request){if(!requestHasSameOrigin(request))return NextResponse.json({error:"Invalid request origin"},{status:403});if(!(await requirePageAccess(request,KEY,"edit").catch(()=>null)))return NextResponse.json({error:"Forbidden"},{status:403});const b=await request.json().catch(()=>null) as Record<string,unknown>|null,id=String(b?.id||"");if(!UUID.test(id))return NextResponse.json({error:"Invalid plan"},{status:400});let update:Record<string,unknown>;if(b?.kind==="markers"){const ms=markers(b.markers);if(!ms)return NextResponse.json({error:"Invalid markers"},{status:400});update={markers:ms};}else{const parsed=input(b);if(!parsed)return NextResponse.json({error:"Invalid plan"},{status:400});update=parsed;}try{if(backend()==="postgres"){const r=await getPostgresPool().query(`update public.operation_plans set name=coalesce($2,name),notes=case when $3::boolean then $4 else notes end,map_name=coalesce($5,map_name),layers=coalesce($6::jsonb,layers),markers=$7::jsonb,updated_at=now() where id=$1 returning *`,[id,update.name||null,"notes" in update,update.notes||null,update.map_name||null,update.layers?JSON.stringify(update.layers):null,JSON.stringify(update.markers)]);if(!r.rowCount)return NextResponse.json({error:"Plan not found"},{status:404});return NextResponse.json({plan:r.rows[0]});}const r=await supabaseAdmin.from("operation_plans").update({...update,updated_at:new Date().toISOString()}).eq("id",id).select().maybeSingle();if(r.error)throw r.error;if(!r.data)return NextResponse.json({error:"Plan not found"},{status:404});return NextResponse.json({plan:r.data});}catch(e){console.error("[planops] Update failed",e);return NextResponse.json({error:"Failed to update plan"},{status:500});}}
export async function DELETE(request:Request){if(!requestHasSameOrigin(request))return NextResponse.json({error:"Invalid request origin"},{status:403});if(!(await requirePageAccess(request,KEY,"edit").catch(()=>null)))return NextResponse.json({error:"Forbidden"},{status:403});const id=new URL(request.url).searchParams.get("id")||"";if(!UUID.test(id))return NextResponse.json({error:"Invalid plan"},{status:400});try{if(backend()==="postgres")await getPostgresPool().query("delete from public.operation_plans where id=$1",[id]);else{const r=await supabaseAdmin.from("operation_plans").delete().eq("id",id);if(r.error)throw r.error;}return NextResponse.json({ok:true});}catch(e){console.error("[planops] Delete failed",e);return NextResponse.json({error:"Failed to delete plan"},{status:500});}}
