import { NextResponse } from "next/server";
import { getPostgresPool, withPostgresTransaction } from "@/lib/postgres/pool";
import { requestHasSameOrigin, requirePageAccess } from "@/lib/route-permissions";
import { supabaseAdmin } from "@/lib/supabase-admin";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function backend(){const v=process.env.LOGISTICS_DATABASE_BACKEND||"supabase";if(v!=="postgres"&&v!=="supabase")throw new Error("Unknown LOGISTICS_DATABASE_BACKEND");return v;}

async function pgData(platoonId:string|null, transactionsOnly:boolean){
  const pool=getPostgresPool();
  if(transactionsOnly){const r=await pool.query(`select t.id,t.action,t.amount,t.quantity,t.asset_name,t.performed_by,t.notes,t.created_at,t.platoon_id,
    p.name platoon_name,pr.display_name from public.token_transactions t left join public.platoons p on p.id=t.platoon_id
    left join public.profiles pr on pr.id=t.performed_by where t.action=any($1::text[]) order by t.created_at desc limit 2000`,[["ADD_TOKENS","BUY_ASSET","REMOVE_ASSET"]]);
    return {transactions:r.rows.map(x=>({...x,platoon:x.platoon_name?{name:x.platoon_name}:null,profile:x.display_name?{display_name:x.display_name}:null}))};}
  const platoons=await pool.query("select * from public.platoons order by sort_order nulls last,name");
  if(!platoonId)return {platoons:platoons.rows,assets:[],ownedAssets:[],transactions:[]};
  const selected=platoons.rows.find(p=>p.id===platoonId);if(!selected)throw new Error("NOT_FOUND");
  const full=/company|blinds basket/i.test(selected.name);
  const [assets,owned,transactions]=await Promise.all([
    pool.query(`select * from public.hq_assets ${full?"":"where category='platoon'"} order by name`),
    pool.query(`select pa.id,pa.quantity,a.id asset_id,a.name asset_name,a.token_cost,a.description,a.inventory,a.category
      from public.platoon_assets pa left join public.hq_assets a on a.id=pa.asset_id where pa.platoon_id=$1`,[platoonId]),
    pool.query("select * from public.token_transactions where platoon_id=$1 order by created_at desc",[platoonId]),
  ]);
  return {platoons:platoons.rows,assets:assets.rows,transactions:transactions.rows,ownedAssets:owned.rows.map(x=>({id:x.id,quantity:x.quantity,asset:x.asset_id?{id:x.asset_id,name:x.asset_name,token_cost:Number(x.token_cost),description:x.description,inventory:Number(x.inventory),category:x.category}:null}))};
}

async function sbData(platoonId:string|null,transactionsOnly:boolean){
  if(transactionsOnly){const r=await supabaseAdmin.from("token_transactions").select("id,action,amount,quantity,asset_name,performed_by,notes,created_at,platoon_id,platoon:platoon_id(name),profile:performed_by(display_name)").in("action",["ADD_TOKENS","BUY_ASSET","REMOVE_ASSET"]).order("created_at",{ascending:false}).limit(2000);if(r.error)throw r.error;return {transactions:r.data||[]};}
  const platoons=await supabaseAdmin.from("platoons").select("*").order("sort_order");if(platoons.error)throw platoons.error;
  if(!platoonId)return {platoons:platoons.data||[],assets:[],ownedAssets:[],transactions:[]};
  const selected=(platoons.data||[]).find(p=>p.id===platoonId);if(!selected)throw new Error("NOT_FOUND");const full=/company|blinds basket/i.test(selected.name);
  let assetQuery=supabaseAdmin.from("hq_assets").select("*");if(!full)assetQuery=assetQuery.eq("category","platoon");
  const [assets,owned,transactions]=await Promise.all([assetQuery.order("name"),supabaseAdmin.from("platoon_assets").select("id,quantity,asset:asset_id(id,name,token_cost,description,inventory,category)").eq("platoon_id",platoonId),supabaseAdmin.from("token_transactions").select("*").eq("platoon_id",platoonId).order("created_at",{ascending:false})]);
  if(assets.error||owned.error||transactions.error)throw assets.error||owned.error||transactions.error;
  return {platoons:platoons.data||[],assets:assets.data||[],ownedAssets:owned.data||[],transactions:transactions.data||[]};
}

export async function GET(request:Request){const url=new URL(request.url),log=url.searchParams.get("scope")==="transactions";
  const access=await requirePageAccess(request,log?"gc.asset-log":"gc.logistics","read").catch(()=>null);if(!access)return NextResponse.json({error:"Forbidden"},{status:403});
  const id=url.searchParams.get("platoonId");if(id&&!UUID.test(id))return NextResponse.json({error:"Invalid platoon"},{status:400});
  try{return NextResponse.json(backend()==="postgres"?await pgData(id,log):await sbData(id,log),{headers:{"Cache-Control":"no-store"}});}catch(e){console.error("[gc-logistics] Read failed",e);return NextResponse.json({error:"Failed to load logistics"},{status:500});}}

function cart(value:unknown){if(!Array.isArray(value)||value.length<1||value.length>100)return null;const out:{assetId:string;quantity:number}[]=[];for(const row of value){const r=row as Record<string,unknown>,assetId=String(r.assetId||""),quantity=Number(r.quantity);if(!UUID.test(assetId)||!Number.isInteger(quantity)||quantity<1||quantity>1000)return null;out.push({assetId,quantity});}return out;}

export async function POST(request:Request){if(!requestHasSameOrigin(request))return NextResponse.json({error:"Invalid request origin"},{status:403});const auth=await requirePageAccess(request,"gc.logistics","edit").catch(()=>null);if(!auth)return NextResponse.json({error:"Forbidden"},{status:403});
  const b=await request.json().catch(()=>null) as Record<string,unknown>|null,action=String(b?.action||""),platoonId=String(b?.platoonId||"");if(!UUID.test(platoonId))return NextResponse.json({error:"Invalid platoon"},{status:400});
  try{if(backend()==="postgres")await withPostgresTransaction(async c=>{
    const p=await c.query<{name:string;tokens:number}>("select name,coalesce(tokens,0)::int tokens from public.platoons where id=$1 for update",[platoonId]);if(!p.rows[0])throw new Error("NOT_FOUND");
    if(action==="addTokens"){const amount=Number(b?.amount);if(!Number.isInteger(amount)||amount<1||amount>100000)throw new Error("INVALID");await c.query("update public.platoons set tokens=coalesce(tokens,0)+$2 where id=$1",[platoonId,amount]);await c.query("insert into public.token_transactions(platoon_id,action,amount,quantity,performed_by,notes) values($1,'ADD_TOKENS',$2,0,$3,$4)",[platoonId,amount,auth.userId,`Added ${amount} tokens to ${p.rows[0].name}`]);}
    else if(action==="checkout"){const items=cart(b?.items);if(!items)throw new Error("INVALID");let total=0;const priced=[];for(const item of items){const a=await c.query<{name:string;token_cost:string;inventory:string}>("select name,coalesce(token_cost,0)::text token_cost,coalesce(inventory,0)::text inventory from public.hq_assets where id=$1",[item.assetId]);if(!a.rows[0])throw new Error("INVALID");const cost=Number(a.rows[0].token_cost),inventory=Number(a.rows[0].inventory);if(inventory>0&&item.quantity>inventory)throw new Error("STOCK");total+=cost*item.quantity;priced.push({...item,name:a.rows[0].name,cost});}if(p.rows[0].tokens<total)throw new Error("FUNDS");await c.query("update public.platoons set tokens=tokens-$2 where id=$1",[platoonId,total]);for(const item of priced){await c.query(`insert into public.platoon_assets(platoon_id,asset_id,quantity) values($1,$2,$3) on conflict(platoon_id,asset_id) do update set quantity=public.platoon_assets.quantity+excluded.quantity`,[platoonId,item.assetId,item.quantity]);await c.query("insert into public.token_transactions(platoon_id,action,amount,quantity,asset_id,asset_name,performed_by,notes) values($1,'BUY_ASSET',$2,$3,$4,$5,$6,$7)",[platoonId,item.cost*item.quantity,item.quantity,item.assetId,item.name,auth.userId,`Bought ${item.quantity} x ${item.name} for ${p.rows[0].name} (${item.cost*item.quantity} tokens)`]);}}
    else if(action==="removeAsset"){const ownedId=String(b?.ownedId||""),quantity=Number(b?.quantity);if(!UUID.test(ownedId)||!Number.isInteger(quantity)||quantity<1)throw new Error("INVALID");const o=await c.query<{quantity:number;asset_id:string;name:string}>(`select pa.quantity,pa.asset_id,a.name from public.platoon_assets pa join public.hq_assets a on a.id=pa.asset_id where pa.id=$1 and pa.platoon_id=$2 for update`,[ownedId,platoonId]);if(!o.rows[0]||quantity>o.rows[0].quantity)throw new Error("INVALID");if(quantity===o.rows[0].quantity)await c.query("delete from public.platoon_assets where id=$1",[ownedId]);else await c.query("update public.platoon_assets set quantity=quantity-$2 where id=$1",[ownedId,quantity]);await c.query("insert into public.token_transactions(platoon_id,action,amount,quantity,asset_id,asset_name,performed_by,notes) values($1,'REMOVE_ASSET',0,$2,$3,$4,$5,$6)",[platoonId,quantity,o.rows[0].asset_id,o.rows[0].name,auth.userId,`Removed ${quantity} x ${o.rows[0].name} from ${p.rows[0].name}`]);}else throw new Error("INVALID");
  });else await hostedWrite(action,platoonId,b,auth.userId!);
  return NextResponse.json({ok:true});}catch(e){const m=e instanceof Error?e.message:"";const status=["INVALID","STOCK","FUNDS"].includes(m)?409:m==="NOT_FOUND"?404:500;if(status===500)console.error("[gc-logistics] Write failed",e);return NextResponse.json({error:m==="FUNDS"?"Not enough tokens":m==="STOCK"?"Requested quantity exceeds stock":status===500?"Failed to update logistics":"Invalid request"},{status});}}

async function hostedWrite(action:string,platoonId:string,b:Record<string,unknown>|null,userId:string){const p=await supabaseAdmin.from("platoons").select("name,tokens").eq("id",platoonId).single();if(p.error)throw p.error;
  if(action==="addTokens"){const amount=Number(b?.amount);if(!Number.isInteger(amount)||amount<1||amount>100000)throw new Error("INVALID");const u=await supabaseAdmin.from("platoons").update({tokens:Number(p.data.tokens||0)+amount}).eq("id",platoonId);if(u.error)throw u.error;const l=await supabaseAdmin.from("token_transactions").insert({platoon_id:platoonId,action:"ADD_TOKENS",amount,quantity:0,performed_by:userId,notes:`Added ${amount} tokens to ${p.data.name}`});if(l.error)throw l.error;return;}
  if(action==="checkout"){const items=cart(b?.items);if(!items)throw new Error("INVALID");const ids=items.map(x=>x.assetId),a=await supabaseAdmin.from("hq_assets").select("id,name,token_cost,inventory").in("id",ids);if(a.error)throw a.error;let total=0;for(const item of items){const asset=a.data?.find(x=>x.id===item.assetId);if(!asset)throw new Error("INVALID");if(Number(asset.inventory)>0&&item.quantity>Number(asset.inventory))throw new Error("STOCK");total+=Number(asset.token_cost)*item.quantity;}if(Number(p.data.tokens)<total)throw new Error("FUNDS");const u=await supabaseAdmin.from("platoons").update({tokens:Number(p.data.tokens)-total}).eq("id",platoonId);if(u.error)throw u.error;for(const item of items){const asset=a.data!.find(x=>x.id===item.assetId)!;const existing=await supabaseAdmin.from("platoon_assets").select("id,quantity").eq("platoon_id",platoonId).eq("asset_id",item.assetId).maybeSingle();if(existing.error)throw existing.error;const save=existing.data?await supabaseAdmin.from("platoon_assets").update({quantity:Number(existing.data.quantity)+item.quantity}).eq("id",existing.data.id):await supabaseAdmin.from("platoon_assets").insert({platoon_id:platoonId,asset_id:item.assetId,quantity:item.quantity});if(save.error)throw save.error;const log=await supabaseAdmin.from("token_transactions").insert({platoon_id:platoonId,action:"BUY_ASSET",amount:Number(asset.token_cost)*item.quantity,quantity:item.quantity,asset_id:item.assetId,asset_name:asset.name,performed_by:userId,notes:`Bought ${item.quantity} x ${asset.name} for ${p.data.name} (${Number(asset.token_cost)*item.quantity} tokens)`});if(log.error)throw log.error;}return;}
  if(action==="removeAsset"){const ownedId=String(b?.ownedId||""),quantity=Number(b?.quantity);if(!UUID.test(ownedId)||!Number.isInteger(quantity)||quantity<1)throw new Error("INVALID");const o=await supabaseAdmin.from("platoon_assets").select("id,quantity,asset_id,asset:asset_id(name)").eq("id",ownedId).eq("platoon_id",platoonId).single();if(o.error||quantity>Number(o.data.quantity))throw o.error||new Error("INVALID");const assetRaw=o.data.asset as unknown,asset=Array.isArray(assetRaw)?assetRaw[0]:assetRaw as {name?:string}|null;const save=quantity===Number(o.data.quantity)?await supabaseAdmin.from("platoon_assets").delete().eq("id",ownedId):await supabaseAdmin.from("platoon_assets").update({quantity:Number(o.data.quantity)-quantity}).eq("id",ownedId);if(save.error)throw save.error;const log=await supabaseAdmin.from("token_transactions").insert({platoon_id:platoonId,action:"REMOVE_ASSET",amount:0,quantity,asset_id:o.data.asset_id,asset_name:asset?.name||null,performed_by:userId,notes:`Removed ${quantity} x ${asset?.name||"asset"} from ${p.data.name}`});if(log.error)throw log.error;return;}throw new Error("INVALID");}
