import type { Metadata } from "next";
import LegalPage, { LegalSection } from "@/components/legal/LegalPage";
import { LEGAL_CONTACT_NAME, LEGAL_OPERATOR_NAME } from "@/config/legal";

export const metadata: Metadata = {
  title: "Privacy Notice | 101st Doom Battalion",
  description:
    "Privacy Notice for the 101st Doom Battalion website, personnel systems, Discord verification, Steam linking, attendance, awards, and audit records.",
};

const privacySections: LegalSection[] = [
  {
    id: "operator",
    title: "1. Who operates this website",
    paragraphs: [
      `${LEGAL_OPERATOR_NAME} operates this community website for personnel records, operational administration, attendance, account linking, awards, certifications, and related member services.`,
      "This website supports a gaming community and is not an official public authority, military organisation, or official Star Wars, Arma, Discord, Steam, Valve, Bohemia Interactive, Disney, or Lucasfilm service.",
    ],
  },
  {
    id: "contact",
    title: "2. Contact details",
    paragraphs: [
      `For privacy questions, correction requests, deletion requests, or other data-protection enquiries, contact: ${LEGAL_CONTACT_NAME}.`,
    ],
  },
  {
    id: "information-collected",
    title: "3. Information we collect",
    paragraphs: [
      "The website may process member names, callsigns, usernames, email addresses, account and authentication records, Discord user IDs, Discord verification information, Steam IDs, Steam profile information, personnel profiles, ranks, roles, attendance records, certifications, medals, awards, administrative notes, audit logs, security information, IP addresses, and device information where those details are logged by the website, hosting provider, security provider, or authentication provider.",
      "The exact information held for a person depends on whether they are a visitor, registered website user, current member, former member, administrator, or someone using a linking or verification flow.",
    ],
  },
  {
    id: "collection-methods",
    title: "4. How information is collected",
    paragraphs: [
      "Information may be provided directly by users, entered by authorised staff, imported or synchronised from connected community systems, generated by website activity, created during account administration, or received from third-party services such as Discord, Steam, Supabase, hosting infrastructure, and security infrastructure.",
      "Steam linking uses Steam OpenID to confirm the Steam ID returned by Steam. Discord verification uses a short-lived verification code sent through the 101st Discord bot to the Discord account already stored against a personnel record.",
    ],
  },
  {
    id: "uses",
    title: "5. Why information is used",
    paragraphs: [
      "Information is used to operate the website, manage member accounts, maintain personnel records, support attendance and training administration, display service records, assign ranks and roles, record certifications, record medals and awards, verify account linking, secure the website, investigate misuse, and maintain audit history.",
      "Information is also used to support Arma-related statistics, XP tracking, and community administration where a member has linked the relevant account information.",
    ],
  },
  {
    id: "lawful-bases",
    title: "6. Lawful bases for processing",
    paragraphs: [
      "Depending on context, the website may process information because it is necessary to provide requested website and community services, because the community has a legitimate interest in operating secure member administration systems, because records are needed for community governance and moderation, because legal obligations apply, or because a person has chosen to provide optional information.",
      "Where optional features are offered, such as linking Steam information to a personnel record, the feature can only operate if the relevant information is provided.",
    ],
  },
  {
    id: "account-administration",
    title: "7. Account administration",
    paragraphs: [
      "Account records may include email addresses, authentication identifiers, session information, role records, permissions, and login-related security information.",
      "These records are used to allow authorised access, restrict administrative areas, prevent unauthorised use, and maintain accountability for changes made through the website.",
    ],
  },
  {
    id: "personnel-management",
    title: "8. Personnel management",
    paragraphs: [
      "Personnel records may include names, callsigns, ranks, roles, billets, time in grade, status history, service records, administrative notes, and related profile information.",
      "Personnel information is used to manage the 101st Doom Battalion roster, display current records, support transfers, and maintain continuity for current and former members.",
    ],
  },
  {
    id: "attendance",
    title: "9. Attendance management",
    paragraphs: [
      "Attendance records may include event attendance, non-attendance, excuses, weekly summaries, Discord attendance responses, timestamps, and staff-entered corrections.",
      "Attendance information is used for operational planning, unit administration, role assignment for events, historical attendance review, and related community management.",
    ],
  },
  {
    id: "discord-verification",
    title: "10. Discord verification",
    paragraphs: [
      "Discord user IDs and verification records may be used to confirm that a person selecting a personnel record controls the Discord account already linked to that record.",
      "Verification codes are short-lived. The code is not intended to be stored in readable form, and verification attempts may be logged for security, abuse prevention, and troubleshooting.",
    ],
  },
  {
    id: "steam-linking",
    title: "11. Steam account linking",
    paragraphs: [
      "Steam account linking uses Steam OpenID to confirm the Steam ID controlled by the person completing the linking flow. The website does not receive Steam passwords, Steam Guard codes, wallet information, inventory information, trades, or private Steam account credentials.",
      "The website may store Steam ID, Steam display name, Steam profile URL, Steam avatar URL, linking status, timestamps, and audit records so the Steam account can be connected to the correct personnel profile for Arma XP and stat tracking.",
    ],
  },
  {
    id: "service-records",
    title: "12. Certifications, medals, and service records",
    paragraphs: [
      "The website may store and display certifications, medals, awards, XP, kill statistics, death statistics, medical tracking statistics, weekly summaries, and service history.",
      "Some awards or statistics may be created automatically from tracked activity, while others may be entered or corrected by authorised staff.",
    ],
  },
  {
    id: "security-audit",
    title: "13. Website security and audit logging",
    paragraphs: [
      "Audit logs and security logs may record user IDs, personnel IDs, actions taken, timestamps, request information, IP addresses, device information, and error information where needed to secure the website and investigate issues.",
      "Audit logs help prevent unauthorised changes, support accountability, and allow staff to diagnose problems with account linking, personnel updates, attendance records, and administrative actions.",
    ],
  },
  {
    id: "providers",
    title: "14. Service providers and data recipients",
    paragraphs: [
      "Information may be processed by service providers that help operate the website, including Supabase, the website hosting provider, Cloudflare if used for DNS, caching, security, or proxy services, Discord, Steam or Valve, and email providers if email functionality is configured.",
      "Information may also be visible to authorised 101st Doom Battalion staff where needed for community administration and technical support.",
    ],
  },
  {
    id: "supabase",
    title: "15. Supabase",
    paragraphs: [
      "Supabase is used for database and authentication features in this project. Supabase may process account data, authentication data, personnel data, attendance data, audit records, and other database records needed by the website.",
      "Supabase authentication may use browser storage and cookies or tokens necessary to keep users signed in and protect sessions.",
    ],
  },
  {
    id: "hosting-cloudflare",
    title: "16. Hosting provider and Cloudflare",
    paragraphs: [
      "The website hosting provider may process technical logs, IP addresses, request information, and device information needed to serve the website, diagnose errors, and protect the service.",
      ],
  },
  {
    id: "discord-steam-email",
    title: "17. Discord, Steam/Valve, and email providers",
    paragraphs: [
      "Discord may process Discord user IDs, server membership information, bot messages, attendance interactions, role assignments, and verification messages when website features interact with Discord.",
      "Steam processes Steam sign-in through Steam OpenID and may provide public Steam profile information."],
  },
  {
    id: "international-transfers",
    title: "18. International data transfers",
    paragraphs: [
      "The website and its service providers may process information in countries outside the United Kingdom. This can happen when cloud hosting, database, security, Discord, Steam, or email services operate internationally.",
      "Where relevant, the website relies on the safeguards and contractual arrangements provided by those service providers.",
    ],
  },
  {
    id: "retention",
    title: "19. Data retention",
    paragraphs: [
      "Information is kept only for as long as reasonably needed for the purposes described in this notice, including active membership administration, security, audit history, dispute resolution, service records, and technical troubleshooting.",
      "Some weekly activity records may reset or roll over while lifetime profile totals, audit records, service records, or historical records may be retained for longer where they support community administration.",
    ],
  },
  {
    id: "leavers",
    title: "20. What happens when a member leaves",
    paragraphs: [
      "When a member leaves, the website may retain a limited personnel history, rank history, awards, audit logs, and administrative records where needed for community records, moderation, security, or continuity.",
      "Access permissions, Discord roles, or active status may be removed or changed. Some public or internal profile information may be archived rather than immediately deleted.",
    ],
  },
  {
    id: "rights",
    title: "21. User data-protection rights",
    paragraphs: [
      "Depending on applicable law, users may have rights to request access, correction, deletion, restriction, objection, portability, or review of certain information held about them.",
      "These rights may be limited where information must be kept for security, audit, legal, community governance, or legitimate administrative reasons.",
    ],
  },
  {
    id: "correction-deletion",
    title: "22. Correction and deletion requests",
    paragraphs: [
      "Requests to correct or delete information should be sent using the contact details in this notice. Please include enough detail to identify the relevant account, personnel record, or linked service.",
      "The website may need to verify the requester before making changes to account, personnel, Discord, Steam, attendance, award, or audit information.",
    ],
  },
  {
    id: "complaints-changes",
    title: "23. Complaints and changes to this notice",
    paragraphs: [
      "Privacy concerns should first be raised using the contact details in this notice so the issue can be reviewed by the website operator.",
      "This Privacy Notice may be updated as the website, community tools, legal requirements, or service providers change. The Last Updated date and version on this page show the current published version.",
    ],
  },
];

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Notice"
      intro="This notice explains how the 101st Doom Battalion website handles personal information for accounts, personnel records, Discord verification, Steam linking, attendance, awards, audit logs, and website security."
      sections={privacySections}
    />
  );
}
