insert into public.awards (
  code,
  name,
  description,
  category,
  icon_key,
  ribbon_color,
  award_type,
  trigger_domain,
  trigger_metric,
  trigger_threshold,
  sort_order
)
values
  (
    'CLANKER_BREAKER_RIBBON',
    'Clanker Breaker Ribbon',
    'Automatically intended for personnel who destroy 500 tracked targets across Arma operations.',
    'Combat',
    'swords',
    '#22c55e',
    'automatic',
    'combat',
    'lifetime_kills',
    500,
    100
  ),
  (
    'DROID_REAPER_MEDAL',
    'Droid Reaper Medal',
    'Automatically intended for personnel who destroy 2000 tracked targets across Arma operations.',
    'Combat',
    'swords',
    '#16a34a',
    'automatic',
    'combat',
    'lifetime_kills',
    2000,
    110
  ),
  (
    'SEPARATIST_BANE_STAR',
    'Separatist Bane Star',
    'Automatically intended for personnel who destroy 6000 tracked targets across Arma operations.',
    'Combat',
    'star',
    '#facc15',
    'automatic',
    'combat',
    'lifetime_kills',
    6000,
    120
  ),
  (
    'IRON_WALKER_BADGE',
    'Iron Walker Badge',
    'Automatically intended for personnel who destroy 25 tracked vehicle, APC, IFV, or tank targets.',
    'Combat',
    'swords',
    '#fb923c',
    'automatic',
    'combat',
    'vehicle_kills',
    25,
    130
  ),
  (
    'BESKAR_BREAKER_BADGE',
    'Beskar Breaker Badge',
    'Automatically intended for personnel who destroy 100 tracked vehicle, APC, IFV, or tank targets.',
    'Combat',
    'shield',
    '#f97316',
    'automatic',
    'combat',
    'vehicle_kills',
    100,
    140
  ),
  (
    'TITANFALL_CROSS',
    'Titanfall Cross',
    'Automatically intended for personnel who destroy 300 tracked vehicle, APC, IFV, or tank targets.',
    'Combat',
    'star',
    '#ea580c',
    'automatic',
    'combat',
    'vehicle_kills',
    300,
    150
  ),
  (
    'SKYFALL_MARK',
    'Skyfall Mark',
    'Automatically intended for personnel who destroy 75 tracked aircraft or air targets.',
    'Combat',
    'swords',
    '#60a5fa',
    'automatic',
    'combat',
    'aircraft_kills',
    75,
    160
  ),
  (
    'SKYHUNTER_CREST',
    'Skyhunter Crest',
    'Automatically intended for personnel who destroy 200 tracked aircraft or air targets.',
    'Combat',
    'shield',
    '#38bdf8',
    'automatic',
    'combat',
    'aircraft_kills',
    200,
    170
  ),
  (
    'VOID_SUPERIORITY_STAR',
    'Void Superiority Star',
    'Automatically intended for personnel who destroy 500 tracked aircraft or air targets.',
    'Combat',
    'star',
    '#0ea5e9',
    'automatic',
    'combat',
    'aircraft_kills',
    500,
    180
  ),
  (
    'KAMINO_LIFESAVER_MEDAL',
    'Kamino Lifesaver Medal',
    'Automatically intended for medics who restart 100 hearts through tracked medical actions.',
    'Medical',
    'medical',
    '#ef4444',
    'automatic',
    'medical',
    'heart_restarts',
    100,
    200
  ),
  (
    'KAMINO_GUARDIAN_CROSS',
    'Kamino Guardian Cross',
    'Automatically intended for medics who restart 250 hearts through tracked medical actions.',
    'Medical',
    'shield',
    '#f43f5e',
    'automatic',
    'medical',
    'heart_restarts',
    250,
    210
  ),
  (
    'JEDI_LIFELINE_STAR',
    'Jedi Lifeline Star',
    'Automatically intended for medics who restart 500 hearts through tracked medical actions.',
    'Medical',
    'star',
    '#fb7185',
    'automatic',
    'medical',
    'heart_restarts',
    500,
    220
  ),
  (
    'BACTA_FLOW_RIBBON',
    'Bacta Flow Ribbon',
    'Automatically intended for medics who administer 100 litres of tracked plasma support.',
    'Medical',
    'medical',
    '#dc2626',
    'automatic',
    'medical',
    'plasma_litres',
    100,
    230
  ),
  (
    'BACTA_SURGE_MEDAL',
    'Bacta Surge Medal',
    'Automatically intended for medics who administer 300 litres of tracked plasma support.',
    'Medical',
    'medical',
    '#b91c1c',
    'automatic',
    'medical',
    'plasma_litres',
    300,
    240
  ),
  (
    'KAMINO_TIDE_CROSS',
    'Kamino Tide Cross',
    'Automatically intended for medics who administer 750 litres of tracked plasma support.',
    'Medical',
    'star',
    '#991b1b',
    'automatic',
    'medical',
    'plasma_litres',
    750,
    250
  ),
  (
    'FIELD_SURGEON_CREST',
    'Field Surgeon Crest',
    'Automatically intended for medics who complete 50 tracked surgeries or fracture reductions.',
    'Medical',
    'medical',
    '#f97316',
    'automatic',
    'medical',
    'surgeries',
    50,
    260
  ),
  (
    'FRACTURE_FORGE_CREST',
    'Fracture Forge Crest',
    'Automatically intended for medics who complete 150 tracked surgeries or fracture reductions.',
    'Medical',
    'shield',
    '#ea580c',
    'automatic',
    'medical',
    'surgeries',
    150,
    270
  ),
  (
    'CYBERNETIC_SURGEON_STAR',
    'Cybernetic Surgeon Star',
    'Automatically intended for medics who complete 400 tracked surgeries or fracture reductions.',
    'Medical',
    'star',
    '#c2410c',
    'automatic',
    'medical',
    'surgeries',
    400,
    280
  ),
  (
    'AIRWAY_GUARDIAN_MARK',
    'Airway Guardian Mark',
    'Automatically intended for medics who complete 150 tracked airway checks or lung treatments.',
    'Medical',
    'medical',
    '#06b6d4',
    'automatic',
    'medical',
    'airway_lung_actions',
    150,
    320
  ),
  (
    'BREATHKEEPER_MEDAL',
    'Breathkeeper Medal',
    'Automatically intended for medics who complete 400 tracked airway checks or lung treatments.',
    'Medical',
    'shield',
    '#0891b2',
    'automatic',
    'medical',
    'airway_lung_actions',
    400,
    330
  ),
  (
    'ATMOS_GUARDIAN_STAR',
    'Atmos Guardian Star',
    'Automatically intended for medics who complete 1000 tracked airway checks or lung treatments.',
    'Medical',
    'star',
    '#0e7490',
    'automatic',
    'medical',
    'airway_lung_actions',
    1000,
    340
  )
on conflict (code) do update
set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  icon_key = excluded.icon_key,
  ribbon_color = excluded.ribbon_color,
  award_type = excluded.award_type,
  trigger_domain = excluded.trigger_domain,
  trigger_metric = excluded.trigger_metric,
  trigger_threshold = excluded.trigger_threshold,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();
