import { createHmac, timingSafeEqual } from "node:crypto";
import { NextResponse } from "next/server";
import { getPostgresPool, withPostgresTransaction } from "@/lib/postgres/pool";
import { requestHasSameOrigin } from "@/lib/route-permissions";
import { supabaseAdmin } from "@/lib/supabase-admin";

export const runtime="nodejs";export const dynamic="force-dynamic";
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const COOKIE="gc_shop_access";const attempts=new Map<string,{count:number;reset:number}>();
function backend(){const v=process.env.LOGISTICS_DATABASE_BACKEND||"supabase";if(v!=="postgres"&&v!=="supabase")throw new Error("Unknown LOGISTICS_DATABASE_BACKEND");return v;}
function secret(){const value=process.env.BETTER_AUTH_SECRET||process.env.AUTH_SECRET;if(!value)throw new Error("AUTH_SECRET is required for shop access");return value;}
function sign(payload:string){return createHmac("sha256",secret()).update(payload).digest("base64url");}
function validCookie(request:Request){const raw=request.headers.get("cookie")?.split(";").map(x=>x.trim()).find(x=>x.startsWith(`${COOKIE}=`))?.slice(COOKIE.length+1);if(!raw)return false;const [exp,sig]=raw.split(".");if(!exp||!sig||Number(exp)<Date.now())return false;const expected=Buffer.from(sign(exp)),actual=Buffer.from(sig);return expected.length===actual.length&&timingSafeEqual(expected,actual);}
function cart(value:unknown){if(!Array.isArray(value)||!value.length||value.length>100)return null;const out:{assetId:string;quantity:number}[]=[];for(const item of value){const row=item as Record<string,unknown>,assetId=String(row.assetId||""),quantity=Number(row.quantity);if(!UUID.test(assetId)||!Number.isInteger(quantity)||quantity<1||quantity>1000)return null;out.push({assetId,quantity});}return out;}

export async function GET(request:Request){const id=new URL(request.url).searchParams.get("platoonId");if(id&&!UUID.test(id))return NextResponse.json({error:"Invalid platoon"},{status:400});try{
  if(backend()==="postgres"){const pool=getPostgresPool(),platoons=await pool.query("select * from public.platoons order by sort_order nulls last,name");if(!id)return NextResponse.json({platoons:platoons.rows,unlocked:validCookie(request)});const p=platoons.rows.find(x=>x.id===id);if(!p)return NextResponse.json({error:"Not found"},{status:404});const full=/company|blinds basket/i.test(p.name);const [assets,owned,tx]=await Promise.all([pool.query(`select * from public.hq_assets ${full?"":"where category='platoon'"} order by name`),pool.query(`select pa.id,pa.quantity,a.id asset_id,a.name asset_name,a.token_cost from public.platoon_assets pa left join public.hq_assets a on a.id=pa.asset_id where pa.platoon_id=$1`,[id]),pool.query("select * from public.token_transactions where platoon_id=$1 order by created_at desc",[id])]);return NextResponse.json({platoons:platoons.rows,assets:assets.rows,ownedAssets:owned.rows.map(x=>({id:x.id,quantity:x.quantity,asset:x.asset_id?{id:x.asset_id,name:x.asset_name,token_cost:Number(x.token_cost)}:null})),transactions:tx.rows,unlocked:validCookie(request)});}
  const platoons=await supabaseAdmin.from("platoons").select("*").order("sort_order");if(platoons.error)throw platoons.error;if(!id)return NextResponse.json({platoons:platoons.data||[],unlocked:validCookie(request)});const p=(platoons.data||[]).find(x=>x.id===id);if(!p)return NextResponse.json({error:"Not found"},{status:404});const full=/company|blinds basket/i.test(p.name);let aq=supabaseAdmin.from("hq_assets").select("*");if(!full)aq=aq.eq("category","platoon");const [assets,owned,tx]=await Promise.all([aq.order("name"),supabaseAdmin.from("platoon_assets").select("id,quantity,asset:asset_id(id,name,token_cost)").eq("platoon_id",id),supabaseAdmin.from("token_transactions").select("*").eq("platoon_id",id).order("created_at",{ascending:false})]);if(assets.error||owned.error||tx.error)throw assets.error||owned.error||tx.error;return NextResponse.json({platoons:platoons.data||[],assets:assets.data||[],ownedAssets:owned.data||[],transactions:tx.data||[],unlocked:validCookie(request)});
}catch(e){console.error("[gc-shop] Read failed",e);return NextResponse.json({error:"Failed to load shop"},{status:500});}}

export async function POST(request:Request){if(!requestHasSameOrigin(request))return NextResponse.json({error:"Invalid request origin"},{status:403});const body=await request.json().catch(()=>null) as Record<string,unknown>|null,action=String(body?.action||"");
  if(action==="unlock"){const ip=request.headers.get("x-forwarded-for")?.split(",")[0]||"local",now=Date.now(),entry=attempts.get(ip);if(entry&&entry.reset>now&&entry.count>=5)return NextResponse.json({error:"Too many attempts"},{status:429});attempts.set(ip,{count:entry&&entry.reset>now?entry.count+1:1,reset:now+60000});const password=String(body?.password||"").slice(0,200);let ok=false;try{if(backend()==="postgres"){const r=await getPostgresPool().query<{ok:boolean}>("select public.check_shop_password($1) ok",[password]);ok=Boolean(r.rows[0]?.ok);}else{const r=await supabaseAdmin.rpc("check_shop_password",{password_input:password});if(r.error)throw r.error;ok=r.data===true;}}catch(e){console.error("[gc-shop] Unlock failed",e);return NextResponse.json({error:"Unable to verify password"},{status:500});}if(!ok)return NextResponse.json({error:"Incorrect password"},{status:401});attempts.delete(ip);const exp=String(Date.now()+8*60*60*1000),response=NextResponse.json({ok:true});response.cookies.set(COOKIE,`${exp}.${sign(exp)}`,{httpOnly:true,sameSite:"strict",secure:process.env.NODE_ENV==="production",path:"/",maxAge:8*60*60});return response;}
  if(action!=="checkout"||!validCookie(request))return NextResponse.json({error:"Shop access required"},{status:403});const platoonId=String(body?.platoonId||""),items=cart(body?.items);if(!UUID.test(platoonId)||!items)return NextResponse.json({error:"Invalid purchase"},{status:400});try{if(backend()==="postgres")await withPostgresTransaction(async c=>{const p=await c.query<{tokens:number}>("select coalesce(tokens,0)::int tokens from public.platoons where id=$1 for update",[platoonId]);if(!p.rows[0])throw new Error("INVALID");let total=0;const prices=[];for(const item of items){const a=await c.query<{token_cost:string;inventory:string}>("select coalesce(token_cost,0)::text token_cost,coalesce(inventory,0)::text inventory from public.hq_assets where id=$1",[item.assetId]);if(!a.rows[0])throw new Error("INVALID");const cost=Number(a.rows[0].token_cost),stock=Number(a.rows[0].inventory);if(stock>0&&item.quantity>stock)throw new Error("STOCK");total+=cost*item.quantity;prices.push({...item,cost});}if(p.rows[0].tokens<total)throw new Error("FUNDS");await c.query("update public.platoons set tokens=tokens-$2 where id=$1",[platoonId,total]);for(const item of prices)await c.query("insert into public.platoon_assets(platoon_id,asset_id,quantity) values($1,$2,$3) on conflict(platoon_id,asset_id) do update set quantity=public.platoon_assets.quantity+excluded.quantity",[platoonId,item.assetId,item.quantity]);await c.query("insert into public.token_transactions(platoon_id,action,amount,quantity,notes) values($1,'BUY_ASSET',$2,0,'Platoon shop checkout')",[platoonId,total]);});else await hostedCheckout(platoonId,items);return NextResponse.json({ok:true});}catch(e){const m=e instanceof Error?e.message:"";return NextResponse.json({error:m==="FUNDS"?"Not enough tokens":m==="STOCK"?"Requested quantity exceeds stock":"Failed to complete purchase"},{status:m==="FUNDS"||m==="STOCK"?409:500});}}

async function hostedCheckout(platoonId:string,items:{assetId:string;quantity:number}[]){const p=await supabaseAdmin.from("platoons").select("tokens").eq("id",platoonId).single(),a=await supabaseAdmin.from("hq_assets").select("id,token_cost,inventory").in("id",items.map(x=>x.assetId));if(p.error||a.error)throw p.error||a.error;let total=0;for(const item of items){const asset=a.data?.find(x=>x.id===item.assetId);if(!asset)throw new Error("INVALID");if(Number(asset.inventory)>0&&item.quantity>Number(asset.inventory))throw new Error("STOCK");total+=Number(asset.token_cost)*item.quantity;}if(Number(p.data.tokens)<total)throw new Error("FUNDS");let r=await supabaseAdmin.from("platoons").update({tokens:Number(p.data.tokens)-total}).eq("id",platoonId);if(r.error)throw r.error;for(const item of items){const e=await supabaseAdmin.from("platoon_assets").select("id,quantity").eq("platoon_id",platoonId).eq("asset_id",item.assetId).maybeSingle();if(e.error)throw e.error;r=e.data?await supabaseAdmin.from("platoon_assets").update({quantity:Number(e.data.quantity)+item.quantity}).eq("id",e.data.id):await supabaseAdmin.from("platoon_assets").insert({platoon_id:platoonId,asset_id:item.assetId,quantity:item.quantity});if(r.error)throw r.error;}r=await supabaseAdmin.from("token_transactions").insert({platoon_id:platoonId,action:"BUY_ASSET",amount:total,quantity:0,notes:"Platoon shop checkout"});if(r.error)throw r.error;}
